#hey, don't check in passwords here.

development:
  adapter: postgresql
  database: rubymn_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rubymn_test
  pool: 5
  timeout: 5000
