# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#hey, don't check in passwords here. 


development:
  adapter: postgresql
  database: tcrbb_dev
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: tcrbb_prod
  username: root
  socket: /var/run/mysqld/mysqld.sock



